create table if not exists public.gig_requests (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  email text not null,
  phone text,
  service text not null,
  details text,
  budget text,
  timeline text
);

alter table public.gig_requests enable row level security;

create policy "Anyone can submit a gig request"
on public.gig_requests for insert
to anon
with check (true);
