create table if not exists public.gig_requests (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  email text not null,
  phone text,
  service text not null,
  details text,
  budget text,
  timeline text
);

alter table public.gig_requests enable row level security;

drop policy if exists "Anyone can submit a gig request" on public.gig_requests;
create policy "Anyone can submit a gig request"
on public.gig_requests for insert
to anon
with check (true);

create table if not exists public.tutoring_applications (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  student_name text not null,
  guardian_name text not null,
  email text not null,
  phone text not null,
  subject text not null,
  level text not null,
  schedule text not null,
  session_format text not null,
  details text not null,
  notes text
);

alter table public.tutoring_applications enable row level security;

drop policy if exists "Anyone can submit a tutoring application" on public.tutoring_applications;
create policy "Anyone can submit a tutoring application"
on public.tutoring_applications for insert
to anon
with check (true);

create table if not exists public.testimonials (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  testimonial text not null,
  rating smallint not null default 5 check (rating between 1 and 5)
);

alter table public.testimonials enable row level security;

drop policy if exists "Anyone can submit a testimonial" on public.testimonials;
create policy "Anyone can submit a testimonial"
on public.testimonials for insert
to anon
with check (true);
