import { useState } from 'react';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faFacebookF, faInstagram, faLinkedinIn } from '@fortawesome/free-brands-svg-icons';
import Brand from '../components/Brand';
import TutoringForm from '../components/TutoringForm';

export default function ApplyPage() {
  const [menuOpen, setMenuOpen] = useState(false);
  return <><header className="site-header"><Brand /><button className="menu-toggle" aria-expanded={menuOpen} onClick={() => setMenuOpen(!menuOpen)}>Menu <span>{menuOpen ? '−' : '+'}</span></button><nav className={`main-nav ${menuOpen ? 'is-open' : ''}`} aria-label="Application page navigation"><a href="/#services">Services</a><a href="/#work">Our work</a><a href="/#about">About</a><a className="nav-cta" href="/">Back home <span>↗</span></a></nav></header><main className="apply-page"><TutoringForm /></main><footer className="site-footer"><div className="section-wrap footer-top"><div className="footer-brand"><Brand /><p>Building the future,<br />one line of code at a time.</p></div><div className="footer-column"><h3>Explore</h3><a href="/#services">Services</a><a href="/#work">Our work</a><a href="/#about">About us</a><a href="/#contact">Contact</a></div><div className="footer-column"><h3>Contact</h3><a href="mailto:hello@techbridgeinfinitygrid.com">hello@techbridgeinfinitygrid.com</a><a href="https://wa.me/2348102445683" target="_blank" rel="noreferrer">0810 244 5683</a><a href="https://wa.me/2349072886986" target="_blank" rel="noreferrer">0907 288 6986</a><span>Akwa Ibom, Nigeria</span></div><div className="footer-column footer-social"><h3>Follow along</h3><div className="socials"><a href="#" aria-label="Facebook"><FontAwesomeIcon icon={faFacebookF} /></a><a href="#" aria-label="Instagram"><FontAwesomeIcon icon={faInstagram} /></a><a href="#" aria-label="LinkedIn"><FontAwesomeIcon icon={faLinkedinIn} /></a></div></div></div><div className="section-wrap footer-bottom"><span>© 2026 TechBridge Infinity Grid. All rights reserved.</span><span>Digital products for a growing Nigeria.</span></div></footer></>;
}
