import { useState } from 'react';
import { createClient } from '@supabase/supabase-js';

const subjects = ['HTML', 'CSS', 'JavaScript', 'DevOps', 'Other'];
const steps = ['Learner details', 'Learning needs', 'Your goals'];
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL;
const supabaseKey = import.meta.env.VITE_SUPABASE_ANON_KEY;
const supabase = supabaseUrl && supabaseKey ? createClient(supabaseUrl, supabaseKey) : null;

export default function TutoringForm() {
  const [step, setStep] = useState(1);
  const [submitted, setSubmitted] = useState(false);
  async function handleSubmit(event) { event.preventDefault(); if (step !== 3) return; const request = Object.fromEntries(new FormData(event.currentTarget).entries()); if (supabase) { const { error } = await supabase.from('tutoring_applications').insert({ student_name: request.studentName, guardian_name: request.guardianName, email: request.email, phone: request.phone, subject: request.subject, level: request.level, schedule: request.schedule, session_format: request.format, details: request.details, notes: request.notes }); if (error) return; } event.currentTarget.reset(); setSubmitted(true); setStep(1); }
  function nextStep() { setStep((current) => Math.min(3, current + 1)); }
  function previousStep() { setStep((current) => Math.max(1, current - 1)); }
  return <section id="tutoring" className="tutoring-section"><div className="section-wrap tutoring-grid"><div className="tutoring-copy"><p className="eyebrow">Developer tutoring</p><h2>Build skills<br /><em>that ship.</em></h2><p>Apply for focused online tutoring in HTML, CSS, JavaScript, and DevOps, built around your goals.</p><div className="tutoring-points"><span>01 / Clear lessons</span><span>02 / Practical projects</span><span>03 / Personal support</span></div></div><form className="tutoring-form" onSubmit={handleSubmit}><div className="tutoring-form-head"><div><p className="form-title">Apply for tutoring</p><span className="form-step-label">Step {step} of 3 / {steps[step - 1]}</span></div><span className="form-progress-value">{Math.round((step / 3) * 100)}%</span></div><div className="form-progress"><span style={{ width: `${(step / 3) * 100}%` }} /></div>{step === 1 && <div className="tutoring-step"><label>Student name<input name="studentName" required placeholder="Student name" /></label><label>Parent / guardian<input name="guardianName" required placeholder="Full name" /></label><label>Email address<input name="email" type="email" required placeholder="you@email.com" /></label><label>WhatsApp number<input name="phone" type="tel" required placeholder="+234" /></label></div>}{step === 2 && <div className="tutoring-step"><label>Subject<select name="subject" required defaultValue=""><option value="" disabled>Select a subject</option>{subjects.map((subject) => <option key={subject}>{subject}</option>)}</select></label><label>Level<select name="level" required defaultValue=""><option value="" disabled>Select your level</option><option>Beginner</option><option>Intermediate</option><option>Advanced</option></select></label><label>Preferred schedule<select name="schedule" required defaultValue=""><option value="" disabled>Select a schedule</option><option>Weekday mornings</option><option>Weekday afternoons</option><option>Weekday evenings</option><option>Weekend sessions</option></select></label><label>Session format<select name="format" required defaultValue=""><option value="" disabled>Select a format</option><option>One-on-one</option><option>Small group</option></select></label></div>}{step === 3 && <div className="tutoring-step"><label>Learning goals<textarea name="details" required rows="5" placeholder="Tell us the goals, topics, and support needed" /></label><label>Extra notes<textarea name="notes" rows="3" placeholder="Anything else we should know?" /></label></div>}<div className="tutoring-form-actions">{step > 1 && <button className="form-back" type="button" onClick={previousStep}>← Back</button>}{step < 3 ? <button className="button button-dark" type="button" onClick={nextStep}>Continue <span>→</span></button> : <button className="button button-dark" type="submit">Submit application <span>↗</span></button>}</div>{submitted && <p className="tutoring-success" role="status">Thank you. We’ll contact you shortly.</p>}</form></div></section>;
}
